### ISSUE TITLE
.ez file not getting built

### ISSUE THREAD

**Issue by probenx** [rabbitmq/rabbitmq-metronome#12]
Hey,

I am following the rabbitmq plugin development guide, and at the last step
`make dist`
I am not getting a .ez file anywhere.
I am also not getting any errors in the terminal.

Any ideas?

Thanks

**Comment by probenx** [comment]
Found the reason: https://groups.google.com/g/rabbitmq-users/c/0Iq708tAhOM

**Comment by lukebakken** [comment]
We will update the documentation. Thank you for pointing it out - https://github.com/rabbitmq/rabbitmq-website/issues/1072
