### ISSUE TITLE
fatal: Authentication failed for 'https://github.com/rabbitmq/rabbitmq-stream-management.git/'

### ISSUE THREAD

**Issue by shv07** [rabbitmq/rabbitmq-metronome#15]
Hi, I was trying to build the plugin on Ubuntu 18 after installing required libraries mentioned in https://www.rabbitmq.com/plugin-development.html . After I run ```make``` , it tries to perhaps clone a private repo - rabbitmq-stream-management and thus throws error. 

Here is an attached image, would be grateful if someone could provide an insight. Thanks!
![image](https://user-images.githubusercontent.com/25014324/105530279-92930a00-5d0d-11eb-9151-708be419aea8.png)

**Comment by lukebakken** [comment]
Related to #13 

Please try this branch: https://github.com/rabbitmq/rabbitmq-metronome/tree/rabbitmq-metronome-13

**Comment by shv07** [comment]
> Related to #13
> 
> Please try this branch: https://github.com/rabbitmq/rabbitmq-metronome/tree/rabbitmq-metronome-13

Thanks!
