### ISSUE TITLE
Error when make

### ISSUE THREAD

**Issue by jiaxiangwang** [rabbitmq/rabbitmq-metronome#16]
tatus.erl rabbit_federation_sup.erl rabbit_federation_upstream.erl rabbit_federation_upstream_exchange.erl rabbit_federation_util.erl
src/rabbit_federation_util.erl:10: can't find include lib "rabbit/include/amqqueue.hrl"
src/rabbit_federation_util.erl:56: undefined macro 'is_amqqueue/1'
src/rabbit_federation_util.erl:60: undefined macro 'is_amqqueue/1'
src/rabbit_federation_util.erl:65: undefined macro 'is_amqqueue/1'

**Comment by lukebakken** [comment]
Thank you for noticing this and reporting. I am working on it now.

**Comment by lukebakken** [comment]
https://github.com/rabbitmq/rabbitmq-server/issues/5980

**Comment by lukebakken** [comment]
Please give this a try now, thank you.
